
services:
  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - '3004:7000'
    volumes:
      - ./backend:/usr/src/app
    restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: next_frontend
    ports:
      - '3005:3000'
    volumes:
      - ./frontend:/app
    restart: always
    command: sh -c "npm run build && npm start"
